### ISSUE TITLE
At reddit.com/prefs/apps the redirect uri is required

### ISSUE THREAD

**Issue by danrobi11** [hDmtP/reddit_from_terminal#1]
Hi. I just noticed your Reddit project. Im trying to follow your guide but Im getting stuck when `creating app` (https://www.reddit.com/prefs/apps)

I've noclue what `redirect uri` im suppose to add. And its required :/

**Comment by hDmtP** [comment]
You can give any random url of a site in place of `redirect uri`. For example, one of your social account(i.e. reddit, [github](https://github.com/danrobi11), linkedin....)

**Comment by danrobi11** [comment]
Yep working. Thank you much :) Closing.
